import type {
  Product,
  Category,
  Brand,
  Banner,
  FAQ,
  Testimonial,
  StoreSettings,
  Review,
  OrderRequest,
  User,
  Coupon,
  ProductColor,
  InstagramReel,
} from "@/types";
import { ABAYA_SIZES } from "@/lib/fragrance-variants";
import {
  productImage,
  categoryImage,
  heroImage,
  avatarImage,
  promoImage,
} from "@/lib/images";

const slug = (s: string) => ({ _type: "slug" as const, current: s });

function buildVariantStock(sizes: string[], colors: ProductColor[], baseStock = 4) {
  return sizes.flatMap((size) =>
    colors.map((color, i) => ({
      size,
      color: color.name,
      stock: baseStock - (sizes.indexOf(size) % 2) - (i % 2),
    }))
  );
}

const fabrics = {
  black: { name: "Classic Black", hex: "#1A1A1A" },
  navy: { name: "Midnight Navy", hex: "#1E2A3A" },
  taupe: { name: "Warm Taupe", hex: "#A67B5B" },
  stone: { name: "Stone Grey", hex: "#C4B8A8" },
  burgundy: { name: "Deep Burgundy", hex: "#4A2035" },
  emerald: { name: "Forest Emerald", hex: "#1B3D36" },
} as const;

const sizes = [...ABAYA_SIZES];

export const mockSettings: StoreSettings = {
  _id: "settings-1",
  storeName: "Nuhaya Collective",
  storeDescription:
    "Premium modest wear crafted for the modern woman — flowing abayas in refined fabrics, tailored silhouettes, and timeless elegance.",
  whatsappNumber: "919746807689",
  email: "hello@nuhayacollective.com",
  phone: "+919746807689",
  address: "Srinagar, India",
  socialLinks: {
    instagram: "https://www.instagram.com/nuhayacollective/",
    facebook: "https://facebook.com/nuhayacollective",
  },
  seoTitle: "Nuhaya Collective — Premium Modest Wear & Abayas",
  seoDescription:
    "Shop premium abayas at Nuhaya Collective. Open, closed, kimono, and embroidered styles with WhatsApp ordering and nationwide delivery.",
  currency: "INR",
  currencySymbol: "₹",
};

export const mockCategories: Category[] = [
  { _id: "cat-1", name: "Open Abayas", slug: slug("open-abayas"), description: "Front-open silhouettes for effortless layering", featured: true, order: 1, productCount: 14, imageUrl: categoryImage(0) },
  { _id: "cat-2", name: "Closed Abayas", slug: slug("closed-abayas"), description: "Classic closed styles for everyday elegance", featured: true, order: 2, productCount: 12, imageUrl: categoryImage(1) },
  { _id: "cat-3", name: "Kimono Abayas", slug: slug("kimono-abayas"), description: "Wide sleeves and fluid draping", featured: true, order: 3, productCount: 9, imageUrl: categoryImage(2) },
  { _id: "cat-4", name: "Embroidered", slug: slug("embroidered"), description: "Hand-finished embroidery and embellishment", featured: true, order: 4, productCount: 8, imageUrl: categoryImage(3) },
  { _id: "cat-5", name: "Evening Abayas", slug: slug("evening-abayas"), description: "Occasion-ready statement pieces", featured: true, order: 5, productCount: 6, imageUrl: categoryImage(4) },
  { _id: "cat-6", name: "Prayer Sets", slug: slug("prayer-sets"), description: "Coordinated abaya and hijab sets", featured: false, order: 6, productCount: 5, imageUrl: categoryImage(5) },
];

export const mockBrands: Brand[] = [
  { _id: "brand-1", name: "Nuhaya Signature", slug: slug("nuhaya-signature"), description: "House collection of premium abayas" },
  { _id: "brand-2", name: "Lumière", slug: slug("lumiere"), description: "Occasion and evening styles" },
  { _id: "brand-3", name: "Atelier Modest", slug: slug("atelier-modest"), description: "Artisan embroidery and detailing" },
];

export const mockInstagramReels: InstagramReel[] = [
  { _id: "reel-1", title: "Open Abaya Styling", caption: "How we layer our signature open abaya", reelUrl: "https://www.instagram.com/p/DZxI9mdS3tf/", thumbnailUrl: productImage(0), productId: "prod-1", productName: "Luna Open Abaya", featured: true, order: 1 },
  { _id: "reel-2", title: "Kimono Drape", caption: "Fluid sleeves for everyday elegance", reelUrl: "https://www.instagram.com/reel/DZzf3-nzkSk/", thumbnailUrl: productImage(2), productId: "prod-3", productName: "Sahara Kimono Abaya", featured: true, order: 2 },
  { _id: "reel-3", title: "Embroidery Detail", caption: "Close-up of hand-finished threadwork", reelUrl: "https://www.instagram.com/reel/DZr62FoT6x0/", thumbnailUrl: productImage(4), productId: "prod-5", productName: "Noor Embroidered Abaya", featured: true, order: 3 },
  { _id: "reel-4", title: "Evening Look", caption: "Occasion abaya pairing ideas", reelUrl: "https://www.instagram.com/reel/DZh7D0SzoU6/", thumbnailUrl: productImage(6), productId: "prod-7", productName: "Celeste Evening Abaya", featured: true, order: 4 },
  { _id: "reel-5", title: "Prayer Set", caption: "Complete modest set reveal", reelUrl: "https://www.instagram.com/reel/DZ2poCazVnD/", thumbnailUrl: productImage(8), productId: "prod-9", productName: "Amara Prayer Set", featured: true, order: 5 },
];

export const mockAboutStoryReel: InstagramReel = {
  _id: "about-reel-1",
  title: "Our Atelier",
  caption: "The craft behind every abaya",
  reelUrl: "https://www.instagram.com/p/DZxI9mdS3tf/",
  thumbnailUrl: heroImage(0),
  featured: true,
  order: 1,
};

export const mockProducts: Product[] = [
  {
    _id: "prod-1",
    name: "Luna Open Abaya",
    slug: slug("luna-open-abaya"),
    shortDescription: "Front-open abaya in premium nida fabric",
    description: "A refined open abaya with clean lines and a fluid drape. Crafted in breathable nida with concealed snap closure — perfect for everyday modest dressing.",
    price: 4499,
    compareAtPrice: 5499,
    stock: 24,
    status: "active",
    featured: true,
    isNewArrival: true,
    isBestSeller: true,
    imageUrl: productImage(0),
    category: mockCategories[0],
    brand: mockBrands[0],
    sizes,
    colors: [fabrics.black, fabrics.navy, fabrics.taupe],
    variantStock: buildVariantStock(sizes, [fabrics.black, fabrics.navy, fabrics.taupe], 4),
    specifications: [
      { key: "Fabric", value: "Premium Nida" },
      { key: "Length", value: "58 inches" },
      { key: "Sleeve", value: "Bell sleeve" },
    ],
    features: ["Breathable fabric", "Concealed snaps", "Modest fit"],
    instagramReels: mockInstagramReels.filter((r) => r.productId === "prod-1"),
    averageRating: 4.9,
    reviewCount: 112,
  },
  {
    _id: "prod-2",
    name: "Amina Closed Abaya",
    slug: slug("amina-closed-abaya"),
    shortDescription: "Classic closed abaya with hidden zip",
    description: "Timeless closed silhouette with a discreet front zip and soft shoulder shaping. An essential wardrobe piece in a weight that drapes beautifully.",
    price: 3999,
    compareAtPrice: 4799,
    stock: 30,
    status: "active",
    featured: true,
    isBestSeller: true,
    imageUrl: productImage(1),
    category: mockCategories[1],
    brand: mockBrands[0],
    sizes,
    colors: [fabrics.black, fabrics.stone, fabrics.burgundy],
    variantStock: buildVariantStock(sizes, [fabrics.black, fabrics.stone, fabrics.burgundy]),
    averageRating: 4.8,
    reviewCount: 89,
  },
  {
    _id: "prod-3",
    name: "Sahara Kimono Abaya",
    slug: slug("sahara-kimono-abaya"),
    shortDescription: "Wide-sleeve kimono abaya with side slits",
    description: "Inspired by Japanese kimono lines, this abaya features exaggerated sleeves and gentle side slits for movement. Lightweight crepe for all-day comfort.",
    price: 5299,
    stock: 18,
    status: "active",
    featured: true,
    isNewArrival: true,
    imageUrl: productImage(2),
    category: mockCategories[2],
    brand: mockBrands[0],
    sizes,
    colors: [fabrics.taupe, fabrics.emerald, fabrics.black],
    variantStock: buildVariantStock(sizes, [fabrics.taupe, fabrics.emerald, fabrics.black]),
    instagramReels: mockInstagramReels.filter((r) => r.productId === "prod-3"),
    averageRating: 4.9,
    reviewCount: 67,
  },
  {
    _id: "prod-4",
    name: "Layla Linen Abaya",
    slug: slug("layla-linen-abaya"),
    shortDescription: "Breathable linen-blend for warm climates",
    description: "A summer-ready abaya in a linen-cotton blend that stays cool and crisp. Relaxed fit with minimal detailing for understated luxury.",
    price: 3699,
    stock: 22,
    status: "active",
    imageUrl: productImage(3),
    category: mockCategories[0],
    brand: mockBrands[0],
    sizes,
    colors: [fabrics.stone, fabrics.taupe],
    variantStock: buildVariantStock(sizes, [fabrics.stone, fabrics.taupe]),
    averageRating: 4.7,
    reviewCount: 45,
  },
  {
    _id: "prod-5",
    name: "Noor Embroidered Abaya",
    slug: slug("noor-embroidered-abaya"),
    shortDescription: "Hand-embroidered bodice and cuffs",
    description: "Delicate tonal embroidery adorns the bodice and sleeve cuffs. A statement piece that transitions seamlessly from day to evening gatherings.",
    price: 7999,
    compareAtPrice: 9499,
    stock: 12,
    status: "active",
    featured: true,
    isBestSeller: true,
    imageUrl: productImage(4),
    category: mockCategories[3],
    brand: mockBrands[2],
    sizes,
    colors: [fabrics.black, fabrics.navy],
    variantStock: buildVariantStock(sizes, [fabrics.black, fabrics.navy], 3),
    instagramReels: mockInstagramReels.filter((r) => r.productId === "prod-5"),
    averageRating: 5,
    reviewCount: 38,
  },
  {
    _id: "prod-6",
    name: "Raya Pleated Abaya",
    slug: slug("raya-pleated-abaya"),
    shortDescription: "Soft pleats through the skirt for volume",
    description: "Vertical pleating creates graceful movement with every step. A contemporary take on classic modest dressing in a mid-weight crepe.",
    price: 5999,
    stock: 15,
    status: "active",
    isNewArrival: true,
    imageUrl: productImage(5),
    category: mockCategories[1],
    brand: mockBrands[0],
    sizes,
    colors: [fabrics.burgundy, fabrics.black],
    variantStock: buildVariantStock(sizes, [fabrics.burgundy, fabrics.black]),
    averageRating: 4.8,
    reviewCount: 29,
  },
  {
    _id: "prod-7",
    name: "Celeste Evening Abaya",
    slug: slug("celeste-evening-abaya"),
    shortDescription: "Satin-trim occasion abaya with belt",
    description: "An occasion abaya with satin facing, crystal button closure, and a matching fabric belt. Designed for weddings, Eid, and formal gatherings.",
    price: 9999,
    compareAtPrice: 11999,
    stock: 8,
    status: "active",
    featured: true,
    isBestSeller: true,
    imageUrl: productImage(6),
    category: mockCategories[4],
    brand: mockBrands[1],
    sizes,
    colors: [fabrics.black, fabrics.emerald, fabrics.burgundy],
    variantStock: buildVariantStock(sizes, [fabrics.black, fabrics.emerald, fabrics.burgundy], 2),
    instagramReels: mockInstagramReels.filter((r) => r.productId === "prod-7"),
    averageRating: 5,
    reviewCount: 24,
  },
  {
    _id: "prod-8",
    name: "Zahra Belted Abaya",
    slug: slug("zahra-belted-abaya"),
    shortDescription: "Defined waist with removable sash",
    description: "A structured abaya with a removable matching sash to define the waist. Clean A-line skirt flatters every figure.",
    price: 4799,
    stock: 20,
    status: "active",
    imageUrl: productImage(7),
    category: mockCategories[0],
    brand: mockBrands[0],
    sizes,
    colors: [fabrics.taupe, fabrics.navy, fabrics.black],
    variantStock: buildVariantStock(sizes, [fabrics.taupe, fabrics.navy, fabrics.black]),
    averageRating: 4.7,
    reviewCount: 56,
  },
  {
    _id: "prod-9",
    name: "Amara Prayer Set",
    slug: slug("amara-prayer-set"),
    shortDescription: "Abaya with matching hijab and bag",
    description: "A complete prayer set including abaya, matching hijab, and carry pouch. Soft jersey fabric packs easily for travel.",
    price: 3499,
    stock: 25,
    status: "active",
    isNewArrival: true,
    imageUrl: productImage(8),
    category: mockCategories[5],
    brand: mockBrands[0],
    sizes,
    colors: [fabrics.black, fabrics.navy, fabrics.stone],
    variantStock: buildVariantStock(sizes, [fabrics.black, fabrics.navy, fabrics.stone], 5),
    instagramReels: mockInstagramReels.filter((r) => r.productId === "prod-9"),
    averageRating: 4.9,
    reviewCount: 71,
  },
  {
    _id: "prod-10",
    name: "Mira Butterfly Abaya",
    slug: slug("mira-butterfly-abaya"),
    shortDescription: "Butterfly sleeve kimono in chiffon overlay",
    description: "A layered chiffon overlay creates dramatic butterfly sleeves. Semi-sheer outer layer over a full lining for modest coverage with editorial flair.",
    price: 6499,
    stock: 14,
    status: "active",
    featured: true,
    imageUrl: productImage(9),
    category: mockCategories[2],
    brand: mockBrands[1],
    sizes,
    colors: [fabrics.stone, fabrics.taupe],
    variantStock: buildVariantStock(sizes, [fabrics.stone, fabrics.taupe], 3),
    averageRating: 4.8,
    reviewCount: 33,
  },
];

export const mockBanners: Banner[] = [
  {
    _id: "banner-1",
    title: "Modest Luxury Redefined",
    subtitle: "New Collection",
    description: "",
    imageUrl: heroImage(0),
    link: "/products",
    buttonText: "Shop Abayas",
    type: "hero",
    active: true,
    order: 1,
  },
  {
    _id: "banner-2",
    title: "Evening Abayas",
    subtitle: "Occasion Edit",
    description: "",
    imageUrl: heroImage(1),
    link: "/products?category=evening-abayas",
    buttonText: "Explore Evening",
    type: "hero",
    active: true,
    order: 2,
  },
  {
    _id: "banner-3",
    title: "Personal Styling",
    subtitle: "Via WhatsApp",
    description: "Not sure about your size or style? Our stylists will guide you to the perfect abaya.",
    imageUrl: promoImage(1200),
    link: "/contact",
    type: "promotional",
    active: true,
    order: 1,
  },
];

export const mockFAQs: FAQ[] = [
  { _id: "faq-1", question: "How do I choose my abaya size?", answer: "Refer to our size guide on each product page. Measure your bust, hips, and preferred length. If between sizes, message us on WhatsApp and we'll recommend the best fit.", order: 1 },
  { _id: "faq-2", question: "What fabrics do you use?", answer: "We use premium nida, crepe, linen-blend, and chiffon depending on the style. Each product listing includes full fabric details.", order: 2 },
  { _id: "faq-3", question: "How do I place an order?", answer: "Select your abaya, choose size and colour, then checkout via WhatsApp. We confirm availability and dispatch within 1–2 business days.", order: 3 },
  { _id: "faq-4", question: "What is your return policy?", answer: "Unworn abayas with original tags may be returned within 7 days. Custom and altered pieces are final sale.", order: 4 },
  { _id: "faq-5", question: "How long does delivery take?", answer: "Standard delivery is 3–7 business days across India. Express shipping is available on request via WhatsApp.", order: 5 },
];

export const mockTestimonials: Testimonial[] = [
  { _id: "test-1", name: "Fatima Rahman", role: "Customer", content: "The Luna Open Abaya is beautifully made — the fabric drapes perfectly and the quality exceeded my expectations.", rating: 5, featured: true, avatarUrl: avatarImage(0) },
  { _id: "test-2", name: "Aisha Khan", role: "Modest fashion blogger", content: "Nuhaya Collective has become my go-to for occasion wear. The Celeste Evening Abaya was stunning at my sister's nikah.", rating: 5, featured: true, avatarUrl: avatarImage(1) },
  { _id: "test-3", name: "Zara Malik", role: "Stylist", content: "I recommend Nuhaya Collective to all my clients looking for premium abayas. Impeccable stitching and thoughtful details.", rating: 5, featured: true, avatarUrl: avatarImage(2) },
];

export const mockReviews: Review[] = [
  { _id: "rev-1", userName: "Khalid M.", rating: 5, title: "Perfect fit", comment: "The Amina Closed Abaya fits beautifully. Arrived in elegant packaging.", verified: true, approved: true, _createdAt: "2026-02-15" },
  { _id: "rev-2", userName: "Sarah L.", rating: 5, title: "Gorgeous embroidery", comment: "Bought the Noor Embroidered Abaya for Eid — received so many compliments.", verified: true, approved: true, _createdAt: "2026-02-10" },
  { _id: "rev-3", userName: "Maryam H.", rating: 4, title: "Lovely kimono style", comment: "The Sahara Kimono Abaya is so comfortable. Slightly longer than expected but beautiful.", verified: true, approved: true, _createdAt: "2026-01-28" },
];

export const mockOrders: OrderRequest[] = [
  {
    _id: "order-1",
    orderNumber: "NA-2026-001",
    type: "cart",
    customer: { name: "Fatima Rahman", phone: "9876543210", email: "fatima@email.com", address: "Kochi, India" },
    items: [{ productId: "prod-1", productName: "Luna Open Abaya", price: 4499, quantity: 1, subtotal: 4499, size: "M", color: "Classic Black" }],
    totalItems: 1,
    grandTotal: 4499,
    status: "pending",
    _createdAt: "2026-06-15",
  },
  {
    _id: "order-2",
    orderNumber: "NA-2026-002",
    type: "cart",
    customer: { name: "Aisha Khan", phone: "9876543211", address: "Bangalore, India" },
    items: [
      { productId: "prod-7", productName: "Celeste Evening Abaya", price: 9999, quantity: 1, subtotal: 9999, size: "L", color: "Classic Black" },
      { productId: "prod-9", productName: "Amara Prayer Set", price: 3499, quantity: 1, subtotal: 3499, size: "M", color: "Midnight Navy" },
    ],
    totalItems: 2,
    grandTotal: 13498,
    status: "confirmed",
    _createdAt: "2026-06-14",
  },
];

export const mockUsers: User[] = [
  { _id: "user-1", name: "Fatima Rahman", email: "fatima@email.com", phone: "9876543210", role: "customer", emailVerified: true },
  { _id: "user-2", name: "Aisha Khan", email: "aisha@email.com", phone: "9876543211", role: "customer", emailVerified: true },
  { _id: "user-3", name: "Admin", email: "admin@nuhayacollective.com", role: "admin", emailVerified: true },
];

export const mockCoupons: Coupon[] = [
  { _id: "coupon-1", code: "NUHAYA10", description: "10% off your first abaya purchase", discountType: "percentage", discountValue: 10, minOrderAmount: 3000, usageLimit: 100, usedCount: 23, active: true },
  { _id: "coupon-2", code: "MODEST500", description: "₹500 off orders above ₹7,000", discountType: "fixed", discountValue: 500, minOrderAmount: 7000, usageLimit: 50, usedCount: 12, active: true },
];

export { ABAYA_SIZES };
